--- #YAML:1.0
name:               SVN-Class
version:            0.12
abstract:           manipulate Subversion workspaces with Perl objects
author:
    - Peter Karman <perl@peknet.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Fast:  0
    Data::Dump:           0
    File::Temp:           0
    IPC::Cmd:             0.40
    IPC::Run:             0
    Path::Class:          0
    Path::Class::File::Stat:  0
    Rose::URI:            0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
