# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVN-Class
version:      0.08_01
version_from: lib/SVN/Class.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    Data::Dump:                    0
    File::Temp:                    0
    IPC::Cmd:                      0
    Path::Class:                   0
    Path::Class::File::Stat:       0
    Rose::URI:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
