--- #YAML:1.0
name:                SVN-Class
version:             0.06
abstract:            manipulate Subversion workspaces with Perl objects
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    Data::Dump:                    0
    IPC::Cmd:                      0
    Path::Class:                   0
    Path::Class::File::Stat:       0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Peter Karman <perl@peknet.com>
